import type { Metadata } from 'next';
import './globals.css';
import { cookies } from 'next/headers';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale } from 'next-intl/server';
import i18n from '@/i18n/config';
import LangSwitcher from '@/components/ui/lang-switcher';
import ThemeChanger from '@/components/ui/theme-changer';
import TimeDisplay from '@/components/ui/time-display';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await cookies();
  const theme = cookie.get('theme')?.value;
  const locale = await getLocale();

  return (
    <html
      lang={locale}
      dir={i18n.locales?.find((l) => l.value === locale)?.dir || 'en'}
      className={`h-full antialiased`}
    >
      <head>
        <link
          id="theme-style"
          rel="stylesheet"
          href={theme === '98' ? '/98.css' : '/xp.css'}
        />
      </head>
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider>
          <div className="flex flex-col grow">
            {children}
            <div className="start-menu">
              <button className="start-button">
                <img src={theme === 'xp' ? '/xp.png' : '/98.png'} />
                Start
              </button>

              <div className="system-tray">
                <LangSwitcher locale={locale} />
                <ThemeChanger theme={theme || 'xp'} />
                <TimeDisplay />
              </div>
            </div>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
