import type { Metadata } from 'next';
import './globals.css';
import { cookies } from 'next/headers';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale } from 'next-intl/server';
import i18n from '@/i18n/config';
import StartMenu from '@/components/layout/start-menu';
import InitLoading from '@/components/layout/init-loading';
import localFont from 'next/font/local';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const iranYekanFont = localFont({
  src: '../public/fonts/iran-yekan.ttf',
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await cookies();
  const theme = cookie.get('theme')?.value;
  const locale = await getLocale();

  return (
    <html
      lang={locale}
      dir={i18n.locales?.find((l) => l.value === locale)?.dir || 'en'}
      className={`h-full antialiased`}
    >
      <head>
        <link
          id="theme-style"
          rel="stylesheet"
          href={theme === '98' ? '/98.css' : '/xp.css'}
        />
      </head>
      <body
        className={`min-h-full flex flex-col ${locale === 'fa' ? iranYekanFont.className : ''}`}
      >
        <NextIntlClientProvider>
          <div className="flex flex-col grow">
            <InitLoading />
            {children}
            <StartMenu theme={theme || 'xp'} locale={locale} />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
